baseURL = "https://sskelkar.github.io/"
title = "Sojjwal Kelkar"
subtitle = "Full Stack Software Engineer"
pygmentsStyle = "trac"
DefaultContentLanguage = "en"
theme = "mini"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
#  homeTitle = "Sojjwal Kelkar"
#  subtitle = "Full Stack Software Engineer"
#  mainSections = ["post","posts"]
#  logo = "img/avatar-icon.png" # Expecting square dimensions
#  favicon = "img/favicon.ico"
  dateFormat = "Jan 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
#  wordCount = true
  useHLJS = true
  socialShare = false
  delayDisqus = true
  showRelatedPosts = true
  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Sojjwal Kelkar"
  email = "sojjwalkelkar@gmail.com"
  github = "sskelkar"
  linkedin = "sskelkar"
  #stackoverflow = "users/XXXXXXX/username"

[[menu.main]]
    name = "Tech Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "Cartoons"
    url = "cartoons"
    weight = 2

[[menu.main]]
    name = "About"
    url = "about"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 5







